version: 2.1

jobs:
  cypress-tests:
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Cypress Tests
          command: npx cypress run --spec "cypress/e2e/Enyata-Assessment/*.cy.js"
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/videos

workflows:
  test-and-report:
    jobs:
      - cypress-tests