version: 2.1

jobs:
  cypress-tests:
    docker:
      - image: cypress/included:15.11.0  # Cypress + dependencies
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run Cypress tests
          command: npx cypress run --spec "cypress/e2e/Enyata-Assessment/*.cy.js"
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/videos

workflows:
  test-and-report:
    jobs:
      - cypress-tests